<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="edytorModel" nsURI="http://www.example.org/edytorModel" nsPrefix="edytorModel">
  <eClassifiers xsi:type="ecore:EClass" name="Operation"/>
  <eClassifiers xsi:type="ecore:EClass" name="Loop" eSuperTypes="#//Operation">
    <eStructuralFeatures xsi:type="ecore:EReference" name="start" lowerBound="1" eType="#//Code"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="end" lowerBound="1" eType="#//Code"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="step" lowerBound="1" eType="#//Code"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="operationsqueue" upperBound="-1"
        eType="#//OperationsQueueElement" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="If" eSuperTypes="#//Operation">
    <eStructuralFeatures xsi:type="ecore:EReference" name="condition" lowerBound="1"
        eType="#//Code" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="elseifqueue" upperBound="-1"
        eType="#//ElseiFQueueElement" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="else" eType="#//Else" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="operationsqueue" upperBound="-1"
        eType="#//OperationsQueueElement" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Code">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="code" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ElseIf" eSuperTypes="#//Operation">
    <eStructuralFeatures xsi:type="ecore:EReference" name="condition" lowerBound="1"
        eType="#//Code" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="operationsqueue" upperBound="-1"
        eType="#//OperationsQueueElement" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="OperationsQueueElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="operation" lowerBound="1"
        eType="#//Operation" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ElseiFQueueElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="elseif" lowerBound="1"
        eType="#//ElseIf" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Else">
    <eStructuralFeatures xsi:type="ecore:EReference" name="code" lowerBound="1" eType="#//Code"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="operationsqueue" upperBound="-1"
        eType="#//OperationsQueueElement" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CodeBlock" eSuperTypes="#//Operation">
    <eStructuralFeatures xsi:type="ecore:EReference" name="code" lowerBound="1" eType="#//Code"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FunctionBlock" eSuperTypes="#//Operation">
    <eStructuralFeatures xsi:type="ecore:EReference" name="operationsqueue" upperBound="-1"
        eType="#//OperationsQueueElement" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="return" eType="#//Code"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="functionName" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//String"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="arguments" upperBound="-1"
        eType="#//Argument" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="functionDef" eType="#//FunctionBlock"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isDef" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Argument">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="value" lowerBound="1" eType="#//Code"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FunctionDefinition">
    <eStructuralFeatures xsi:type="ecore:EReference" name="functions" upperBound="-1"
        eType="#//FunctionBlock" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Class">
    <eStructuralFeatures xsi:type="ecore:EReference" name="functionsdefinition" lowerBound="1"
        eType="#//FunctionDefinition" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="functionblocks" upperBound="-1"
        eType="#//FunctionBlock" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="extends" eType="#//Class"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isThread" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Actor">
    <eStructuralFeatures xsi:type="ecore:EReference" name="operationsqueue" upperBound="-1"
        eType="#//OperationsQueueElement" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
</ecore:EPackage>
